I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/angus.rpy", line 5, in script
    show woodsimg at bg
  File "game/angus.rpy", line 5, in <module>
    show woodsimg at bg
NameError: name 'bg' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/angus.rpy", line 5, in script
    show woodsimg at bg
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/angus.rpy", line 5, in <module>
    show woodsimg at bg
NameError: name 'bg' is not defined

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
sunsunsun 1.0
Mon Mar 22 14:43:35 2021
